# list

# mylist=[2,3,4,1,5,6,7,"apple","banana","orange",15.236,True]
# print(mylist)
# print(type(mylist))
# print(mylist[7])
# print(mylist[11])
# # print(mylist[12])

mylist=[1,1,1,2,3,7,8,9,4,5,6]
mylist.sort()
print(mylist)
mylist.append(10)
mylist.append(11)
print(mylist)
mylist.reverse()
print(mylist)
mylist.remove(11)
mylist.remove(1)
# mylist.remove(1)
# mylist.remove(1)
print(mylist)
print(mylist.count(1))
newList=mylist.copy()
print("newlist",newList)
mylist.pop()
mylist.pop()
mylist.pop()
mylist.pop()
print(mylist)
