employeeName=input("Enter the Employee Name : \n")
employeeAge=int(input("Enter the Employee Age : \n"))
employeeSalary=float(input("Enter the Employee Salary : \n"))
print("Employee Name : ",employeeName)
print("Employee Age : ",employeeAge)
print("Employee Salary : ",employeeSalary)
print(type(employeeName))
print(type(employeeAge))
print(type(employeeSalary))