# Generated by Django 4.1.5 on 2023-02-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
