# Generated by Django 4.1.5 on 2023-02-08 03:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='aboutCourse',
            field=ckeditor.fields.RichTextField(default='aboutCourse'),
        ),
        migrations.AddField(
            model_name='courses',
            name='syllabus',
            field=ckeditor.fields.RichTextField(default='syllabus'),
        ),
    ]
