# Generated by Django 4.1.5 on 2023-02-08 03:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0004_courses_aboutcourse_courses_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
