# Generated by Django 4.1.5 on 2023-02-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
