# Generated by Django 4.1.5 on 2023-02-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0006_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course'),
        ),
    ]
