employe_name=input('enter employe name :')
employe_age=int(input('enter employe age :'))
employe_phone_number=int(input('enter employe phone number :'))
employe_address=input('enter employe address :')
print('Employe Name :',employe_name)
print('Employe age :',employe_age)
print('Employe Phone Number :',employe_phone_number)
print('Employe Address :',employe_address)
print('Employe Name type is:',type(employe_name))
print('Employe age type is:',type(employe_age))
print('Employe phone nuber type is:',type(employe_phone_number))
print('Employe address type is:',type(employe_address))
