# f=open("ark.txt","x")
# f=f.write("Ria Institue of Technology\nRia is at Marathalli Bangalore\nWe are the Developer")
f=open("ark.txt","+r")
f.write("\nDeveloper")
# print(f.read())
# print(f.readline())
# print(f.readline())
d=f.readlines()
print(d[2])
f.close()
