# more on strings
title="ria Institue of Technology"
print(title.upper())
print(title.lower())
print(title.capitalize())
print(title.count('o'))
print(title.endswith('y'))
print(title.endswith('Y'))
print(title.startswith('anees'))
print(title.startswith('ria'))
print(title.replace("ria","ia"))
title=title.upper()
print(title)
print(title.find('T'))
# print(title.index('z'))